config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :todos do
    member do
      patch :move
    end
  end


  namespace :admin do
    resources :users
    resources :announcements
    resources :notifications
    resources :services

    root to: "users#index"
  end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/todo.rb
class Todo < ApplicationRecord
  acts_as_list
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy, :move]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def move
    @todo.insert_at(params[:position].to_i)
    head :ok
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:description, :position)
    end
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/todos/_form.html.erb
<%= form_with(model: todo, local: true) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :position %>
    <%= form.number_field :position, class: 'form-control' %>
  </div>

  <div class="form-group">
    <% if todo.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', todo, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if todo.persisted? %>
      <%= link_to "Cancel", todo, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", todos_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Edit Todo</h1>

<%= render 'form', todo: @todo %>

app/views/todos/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Todos</h1>
  </div>

  <div class="col-sm-6 text-right">
    <%= link_to new_todo_path, class: 'btn btn-primary' do %>
      Add New Todo
    <% end %>
  </div>
</div>

<div data-controller="drag" data-drag-url="/todos/:id/move">
  <% @todos.order(position: :asc).each do |todo| %>
    <div data-id="<%= todo.id %>" class="card card-body mb-4">
      <%= todo.description %>
    </div>
  <% end %>
</div>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render 'form', todo: @todo %>

app/views/todos/show.html.erb
<div class="page-header">
  <%= link_to todos_path, class: 'btn btn-default' do %>
    All Todos
  <% end %>
  <%= link_to edit_todo_path(@todo), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1>Show todo</h1>
</div>

<dl class="dl-horizontal">
  <dt>Description:</dt>
  <dd><%= @todo.description %></dd>

  <dt>Position:</dt>
  <dd><%= @todo.position %></dd>

</dl>